### ISSUE TITLE
Is there any Posibility to add COD Pincode Checker

### ISSUE THREAD

**Issue by vinaykumar9999** [mageprince/Magento2-PincodeChecker#1]
Is there any possibility to check and validate the pin-code by Prepaid Delivery and COD Delivery

Like there are options in the CSV -

Pincode  Prepaid Delivery   COD
123456             YES              YES
234567             YES              NO

And It will validate the results on Checkout page and product page

It will show two options on product page
---------------------------
123456                                   CHECK
---------------------------
-Delivery is possible in this area
-COD is Available

---------------------------
234567                                   CHECK
---------------------------
-Delivery is possible in this area
-COD is Not Available

Regards
Vinay

**Comment by mageprince** [comment]
No, This functionality not available for this version. Maybe I will integrate with next version of this module.
Thank You for your suggestion.

**Comment by rashigoyal14** [comment]
I have a custom module working same for Cash on delivery & Shipping available in M2.
Please check
[PincodeChecker.zip](https://github.com/mageprince/Magento2-PincodeChecker/files/4852138/PincodeChecker.zip)
