### ISSUE TITLE
Undefined property: InstallSchema::$eavSetupFactory

### ISSUE THREAD

**Issue by ghost** [mageprince/Magento2-PincodeChecker#2]
Magento 2.2.2
I got error
Installing schema... Notice: Undefined property: Prince\PincodeChecker\Setup\InstallSchema::$eavSetupFactory 
in {Magento root}\app\code\Prince\PincodeChecker\Setup\InstallSchema.php on line 50

**Comment by mageprince** [comment]
**@abhijeet-satpute**  Thank you for your report. The issue has been resolved. Please download the latest repository and try again.
